WITH PERCENT_TABLE AS (
    SELECT ID, PERCENT_RANK() OVER (
        ORDER BY SIZE_OF_COLONY DESC
    ) COLONY_NAME FROM ECOLI_DATA
)

SELECT ID, 
    CASE 
    WHEN COLONY_NAME <= 0.25 THEN "CRITICAL"
    WHEN COLONY_NAME <= 0.5 THEN "HIGH"
    WHEN COLONY_NAME <= 0.75 THEN "MEDIUM"
    ELSE "LOW" END  COLONY_NAME
    FROM PERCENT_TABLE ORDER BY ID;