SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID=O.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING U.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;