SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, COUNT(DISTINCT U.USER_ID) PUCHASED_USERS, ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021), 1) PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID=O.USER_ID
WHERE YEAR(U.JOINED)=2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;