SELECT H.HISTORY_ID, CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 < 7 THEN 1
WHEN DATEDIFF(END_DATE, START_DATE)+1 < 30 THEN 0.95
WHEN DATEDIFF(END_DATE, START_DATE)+1 < 90 THEN 0.93 
ELSE 0.9 END FEE 
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID=H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE=P.CAR_TYPE
WHERE C.CAR_TYPE="트럭"
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID;

-- 코드를 입력하세요
SELECT H.HISTORY_ID, ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 7 THEN 1 WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 THEN 0.95 WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 THEN 0.92 ELSE 0.85 END)) FEE FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = P.CAR_TYPE AND P.CAR_TYPE = '트럭' GROUP BY H.HISTORY_ID ORDER BY FEE DESC, H.HISTORY_ID DESC;