SET @HOUR = -1;

SELECT @HOUR := @HOUR + 1 HOUR, (
    SELECT COUNT(ANIMAL_ID) FROM ANIMAL_OUTS WHERE HOUR(DATETIME)=@HOUR
) COUNT
FROM ANIMAL_OUTS
WHERE @HOUR BETWEEN -1 AND 22
GROUP BY HOUR
ORDER BY HOUR;
