SELECT DISTINCT I.ID, L.FISH_NAME, L.LENGTH FROM FISH_INFO I JOIN (
    SELECT B.FISH_TYPE, B.FISH_NAME, MAX(IFNULL(A.LENGTH, 10)) LENGTH FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE GROUP BY B.FISH_TYPE, B.FISH_NAME
) L ON I.FISH_TYPE = L.FISH_TYPE AND I.LENGTH = L.LENGTH ORDER BY I.ID;